In [1]:
import pandas as pd
import numpy as np

In [2]:
Model_data = pd.read_csv('finaldata.csv')

**Removing the specific symbols not allowed in some python functions**

In [3]:
Model_data.columns = Model_data.columns.str.replace(' ', '_')
Model_data.rename(columns=lambda x: x.replace("-", "_"), inplace=True)
Model_data.rename(columns=lambda x: x.replace("(", ""), inplace=True)
Model_data.rename(columns=lambda x: x.replace(")", ""), inplace=True)

In [4]:
Model_data.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,StreamingMovies_Yes,Contract_Month_to_month,Contract_One_year,Contract_Two_year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank_transfer_automatic,PaymentMethod_Credit_card_automatic,PaymentMethod_Electronic_check,PaymentMethod_Mailed_check
0,0,1,29.85,29.85,0,1,0,0,1,1,...,0,1,0,0,0,1,0,0,1,0
1,0,34,56.95,1889.50,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,1,1,0,1,...,0,1,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,0,1,1,0,1,...,0,0,1,0,1,0,1,0,0,0
4,0,2,70.70,151.65,1,1,0,1,0,1,...,0,1,0,0,0,1,0,0,1,0

In [5]:
x=Model_data.drop('Churn',axis=1)
x

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,StreamingMovies_Yes,Contract_Month_to_month,Contract_One_year,Contract_Two_year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank_transfer_automatic,PaymentMethod_Credit_card_automatic,PaymentMethod_Electronic_check,PaymentMethod_Mailed_check
0,0,1,29.85,29.85,1,0,0,1,1,0,...,0,1,0,0,0,1,0,0,1,0
1,0,34,56.95,1889.50,0,1,1,0,1,0,...,0,0,1,0,1,0,0,0,0,1
2,0,2,53.85,108.15,0,1,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,1,1,0,1,0,...,0,0,1,0,1,0,1,0,0,0
4,0,2,70.70,151.65,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,0,1,0,1,0,1,...,1,0,1,0,0,1,0,0,0,1
7039,0,72,103.20,7362.90,1,0,0,1,0,1,...,1,0,1,0,0,1,0,1,0,0
7040,0,11,29.60,346.45,1,0,0,1,0,1,...,0,1,0,0,0,1,0,0,1,0
7041,1,4,74.40,306.60,0,1,0,1,1,0,...,0,1,0,0,0,1,0,0,0,1
7042,0,66,105.65,6844.50,0,1,1,0,1,0,...,1,0,0,1,0,1,1,0,0,0

In [6]:
y=Model_data['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

## Splitting - Train/Test

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

pip install catboost

In [9]:
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [10]:
pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in c:\users\shashank\appdata\local\programs\python\python311\lib\site-packages (0.11.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\shashank\appdata\local\programs\python\python311\lib\site-packages (from imbalanced-learn) (1.26.1)
Requirement already satisfied: scipy>=1.5.0 in c:\users\shashank\appdata\local\programs\python\python311\lib\site-packages (from imbalanced-learn) (1.11.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\shashank\appdata\local\programs\python\python311\lib\site-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\shashank\appdata\local\programs\python\python311\lib\site-packages (from imbalanced-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\shashank\appdata\local\programs\python\python311\lib\site-packages (from imbalanced-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

## Using Different Clasifying Models

**Using Catboost Classifier**

In [22]:
from catboost import CatBoostClassifier
catboost_model = CatBoostClassifier(iterations=100,  
                                    depth=6, 
                                    learning_rate=0.1,  
                                    loss_function='Logloss',  
                                    verbose=100)  

catboost_model.fit(x_train, y_train, cat_features=None) 
y_pred = catboost_model.predict(x_test)

accuracy = (y_pred == y_test).mean()
print(f"Accuracy: {accuracy}")

0:	learn: 0.6308652	total: 6.11ms	remaining: 605ms
99:	learn: 0.3557548	total: 486ms	remaining: 0us
Accuracy: 0.8261178140525195

In [23]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.85      0.92      0.89      1023
           1       0.74      0.57      0.64       386

    accuracy                           0.83      1409
   macro avg       0.79      0.75      0.76      1409
weighted avg       0.82      0.83      0.82      1409

**Using RandomForest Classifier**

In [24]:
from sklearn.ensemble import RandomForestClassifier
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)
model_rf.fit(x_train,y_train)
y_pred=model_rf.predict(x_test)
model_rf.score(x_test,y_test)
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.93      0.87      1023
           1       0.72      0.46      0.56       386

    accuracy                           0.80      1409
   macro avg       0.77      0.70      0.72      1409
weighted avg       0.79      0.80      0.79      1409

In [25]:
from imblearn.combine import SMOTETomek
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

#Here I am applying SMOTETomek to the RF classifier
smt = SMOTETomek(random_state=42)
X_resampled, y_resampled = smt.fit_resample(x, y)

xr_train, xr_test, yr_train, yr_test = train_test_split(X_resampled, y_resampled, test_size=0.2)

model_rf_smote = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)
model_rf_smote.fit(xr_train, yr_train)

yr_predict = model_rf_smote.predict(xr_test)

# Calculating the model accuracy and other metrics
model_score_r = model_rf_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.8371488033298647
              precision    recall  f1-score   support

           0       0.87      0.80      0.83       979
           1       0.81      0.88      0.84       943

    accuracy                           0.84      1922
   macro avg       0.84      0.84      0.84      1922
weighted avg       0.84      0.84      0.84      1922

**using Catboost with SMOTETomek**

In [26]:
from imblearn.combine import SMOTETomek
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

smt = SMOTETomek(random_state=42)
X_resampled, y_resampled = smt.fit_resample(x, y)

xr_train, xr_test, yr_train, yr_test = train_test_split(X_resampled, y_resampled, test_size=0.2)

model_catboost_smote = CatBoostClassifier(iterations=100, depth=6, learning_rate=0.1, random_state=100)
model_catboost_smote.fit(xr_train, yr_train)

yr_predict = model_catboost_smote.predict(xr_test)

model_score_catboost = model_catboost_smote.score(xr_test, yr_test)
print(model_score_catboost)
print(metrics.classification_report(yr_test, yr_predict))

0:	learn: 0.6174624	total: 3.79ms	remaining: 375ms
1:	learn: 0.5599821	total: 8.01ms	remaining: 392ms
2:	learn: 0.5153544	total: 12.4ms	remaining: 400ms
3:	learn: 0.4804176	total: 16.4ms	remaining: 393ms
4:	learn: 0.4563188	total: 20.4ms	remaining: 387ms
5:	learn: 0.4245628	total: 24.2ms	remaining: 380ms
6:	learn: 0.4032223	total: 28.4ms	remaining: 377ms
7:	learn: 0.3903698	total: 32.3ms	remaining: 372ms
8:	learn: 0.3794266	total: 36.4ms	remaining: 368ms
9:	learn: 0.3578893	total: 40.6ms	remaining: 366ms
10:	learn: 0.3475186	total: 44.8ms	remaining: 362ms
11:	learn: 0.3413448	total: 48.5ms	remaining: 356ms
12:	learn: 0.3359141	total: 52.6ms	remaining: 352ms
13:	learn: 0.3261541	total: 56.6ms	remaining: 348ms
14:	learn: 0.3190461	total: 60.4ms	remaining: 342ms
15:	learn: 0.3150833	total: 64ms	remaining: 336ms
16:	learn: 0.3097188	total: 67.7ms	remaining: 331ms
17:	learn: 0.3048004	total: 71.3ms	remaining: 325ms
18:	learn: 0.3023581	total: 74.9ms	remaining: 319ms
19:	learn: 0.3001050	total: 78.5ms	remaining: 314ms
20:	learn: 0.2983415	total: 82.1ms	remaining: 309ms
21:	learn: 0.2964326	total: 85.7ms	remaining: 304ms
22:	learn: 0.2944472	total: 89.7ms	remaining: 300ms
23:	learn: 0.2931392	total: 93.6ms	remaining: 296ms
24:	learn: 0.2890345	total: 97.5ms	remaining: 293ms
25:	learn: 0.2879717	total: 101ms	remaining: 288ms
26:	learn: 0.2856463	total: 105ms	remaining: 284ms
27:	learn: 0.2827555	total: 109ms	remaining: 279ms
28:	learn: 0.2795905	total: 112ms	remaining: 275ms
29:	learn: 0.2785488	total: 116ms	remaining: 271ms
30:	learn: 0.2762932	total: 120ms	remaining: 267ms
31:	learn: 0.2755776	total: 123ms	remaining: 262ms
32:	learn: 0.2745809	total: 127ms	remaining: 258ms
33:	learn: 0.2738362	total: 131ms	remaining: 254ms
34:	learn: 0.2731342	total: 135ms	remaining: 251ms
35:	learn: 0.2719613	total: 139ms	remaining: 246ms
36:	learn: 0.2711056	total: 142ms	remaining: 242ms
37:	learn: 0.2693917	total: 146ms	remaining: 238ms
38:	learn: 0.2684755	total: 150ms	remaining: 234ms
39:	learn: 0.2668032	total: 154ms	remaining: 230ms
40:	learn: 0.2663623	total: 157ms	remaining: 226ms
41:	learn: 0.2659090	total: 161ms	remaining: 222ms
42:	learn: 0.2652226	total: 165ms	remaining: 218ms
43:	learn: 0.2642075	total: 168ms	remaining: 214ms
44:	learn: 0.2638288	total: 172ms	remaining: 210ms
45:	learn: 0.2620678	total: 176ms	remaining: 206ms
46:	learn: 0.2612399	total: 179ms	remaining: 202ms
47:	learn: 0.2604095	total: 184ms	remaining: 199ms
48:	learn: 0.2599493	total: 188ms	remaining: 195ms
49:	learn: 0.2591846	total: 191ms	remaining: 191ms
50:	learn: 0.2587528	total: 195ms	remaining: 187ms
51:	learn: 0.2580362	total: 198ms	remaining: 183ms
52:	learn: 0.2577605	total: 202ms	remaining: 179ms
53:	learn: 0.2570899	total: 205ms	remaining: 175ms
54:	learn: 0.2564165	total: 209ms	remaining: 171ms
55:	learn: 0.2557932	total: 213ms	remaining: 168ms
56:	learn: 0.2550717	total: 229ms	remaining: 173ms
57:	learn: 0.2547390	total: 233ms	remaining: 169ms
58:	learn: 0.2539546	total: 237ms	remaining: 165ms
59:	learn: 0.2533799	total: 241ms	remaining: 161ms
60:	learn: 0.2528347	total: 245ms	remaining: 156ms
61:	learn: 0.2524941	total: 248ms	remaining: 152ms
62:	learn: 0.2518268	total: 252ms	remaining: 148ms
63:	learn: 0.2514711	total: 255ms	remaining: 144ms
64:	learn: 0.2506332	total: 259ms	remaining: 140ms
65:	learn: 0.2499053	total: 263ms	remaining: 135ms
66:	learn: 0.2493855	total: 267ms	remaining: 131ms
67:	learn: 0.2489216	total: 270ms	remaining: 127ms
68:	learn: 0.2485401	total: 274ms	remaining: 123ms
69:	learn: 0.2478931	total: 278ms	remaining: 119ms
70:	learn: 0.2474622	total: 281ms	remaining: 115ms
71:	learn: 0.2466548	total: 285ms	remaining: 111ms
72:	learn: 0.2460774	total: 289ms	remaining: 107ms
73:	learn: 0.2455780	total: 292ms	remaining: 103ms
74:	learn: 0.2449907	total: 296ms	remaining: 98.6ms
75:	learn: 0.2443610	total: 300ms	remaining: 94.6ms
76:	learn: 0.2439400	total: 303ms	remaining: 90.6ms
77:	learn: 0.2432032	total: 307ms	remaining: 86.6ms
78:	learn: 0.2427247	total: 311ms	remaining: 82.5ms
79:	learn: 0.2422124	total: 314ms	remaining: 78.5ms
80:	learn: 0.2415900	total: 318ms	remaining: 74.5ms
81:	learn: 0.2407592	total: 321ms	remaining: 70.5ms
82:	learn: 0.2401811	total: 325ms	remaining: 66.6ms
83:	learn: 0.2397039	total: 328ms	remaining: 62.6ms
84:	learn: 0.2391962	total: 332ms	remaining: 58.6ms
85:	learn: 0.2387526	total: 336ms	remaining: 54.7ms
86:	learn: 0.2383000	total: 339ms	remaining: 50.7ms
87:	learn: 0.2378480	total: 343ms	remaining: 46.8ms
88:	learn: 0.2373510	total: 347ms	remaining: 42.9ms
89:	learn: 0.2368230	total: 350ms	remaining: 38.9ms
90:	learn: 0.2360699	total: 354ms	remaining: 35ms
91:	learn: 0.2353694	total: 357ms	remaining: 31.1ms
92:	learn: 0.2349089	total: 361ms	remaining: 27.2ms
93:	learn: 0.2343285	total: 365ms	remaining: 23.3ms
94:	learn: 0.2338035	total: 368ms	remaining: 19.4ms
95:	learn: 0.2334056	total: 372ms	remaining: 15.5ms
96:	learn: 0.2326805	total: 375ms	remaining: 11.6ms
97:	learn: 0.2324167	total: 379ms	remaining: 7.73ms
98:	learn: 0.2316728	total: 383ms	remaining: 3.86ms
99:	learn: 0.2311066	total: 386ms	remaining: 0us
0.8688865764828304
              precision    recall  f1-score   support

           0       0.85      0.88      0.87       945
           1       0.88      0.85      0.87       977

    accuracy                           0.87      1922
   macro avg       0.87      0.87      0.87      1922
weighted avg       0.87      0.87      0.87      1922

**So the final Results are displayed here. Achieved highest accuracy of 86% using Catboost classifier with SMOTETomek.**